// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Security2.Database;

namespace Security2.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190409075456_AddTimePasswords")]
    partial class AddTimePasswords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Security2.Database.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Security2.Database.Entities.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Key");

                    b.Property<string>("Name");

                    b.Property<string>("PasswordHash");

                    b.HasKey("UserGuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Security2.Database.Entities.UserPassword", b =>
                {
                    b.Property<Guid>("UserGuid");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsUsed");

                    b.Property<string>("Password");

                    b.HasKey("UserGuid", "Date");

                    b.ToTable("UserPasswords");
                });

            modelBuilder.Entity("Security2.Database.Entities.UserPassword", b =>
                {
                    b.HasOne("Security2.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
